apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    key: value
    run: nginx
  name: nginx-node-port
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    key: value
    run: nginx
  type: NodePort
status:
  loadBalancer: {}
